In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\dr maha abdallah\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dr maha abdallah\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dr maha abdallah\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\dr maha abdallah\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\dr maha abdallah\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: C:\Users\Dr Maha Abdallah\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [2]:
! pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\dr maha abdallah\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dr maha abdallah\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dr maha abdallah\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\dr maha abdallah\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\dr maha abdallah\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: C:\Users\Dr Maha Abdallah\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

learn pandas

In [3]:
pip install pandas  --default-timeout=100

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\dr maha abdallah\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dr maha abdallah\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dr maha abdallah\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\dr maha abdallah\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\dr maha abdallah\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: C:\Users\Dr Maha Abdallah\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

In [5]:
pd.Series(10)

0    10
dtype: int64

In [6]:
numbers = [10,11,12,13]
pd.Series(numbers)

0    10
1    11
2    12
3    13
dtype: int64

In [7]:
data = pd.Series([10,11,12,13])
type(data.values)

numpy.ndarray

In [8]:
data = pd.Series([10,11,12,13], index = ['frist','second','third','fourth'])
print(data)
data["second"]

frist     10
second    11
third     12
fourth    13
dtype: int64

np.int64(11)

In [9]:
Dictionary = {
    "ahmed":1234,
    "maha":2345,
    "Naglaa":5678,
    "noha":9876
}
student = pd.Series(Dictionary)
print(student)

ahmed     1234
maha      2345
Naglaa    5678
noha      9876
dtype: int64

In [10]:
Dictionary = {
    "ahmed":12,
    "maha":34,
    "Naglaa":56,
    "noha":78
}
id = pd.Series(Dictionary)
print(id)

ahmed     12
maha      34
Naglaa    56
noha      78
dtype: int64

In [11]:
pd.DataFrame(
    {"population" : [12,34,56,78]}
)

   population
0          12
1          34
2          56
3          78

In [12]:
pd.DataFrame(
    {"population" : [12,34,56,78],
     "area" : [1,2,4,6],
     "topic" : [987,234,765,987]}
)

   population  area  topic
0          12     1    987
1          34     2    234
2          56     4    765
3          78     6    987

In [13]:
population_dic = {
    "shiben" : 1234,
    "Tanta" : 9876,
    "Cairo" : 12345
}
population = pd.Series(population_dic)
population

shiben     1234
Tanta      9876
Cairo     12345
dtype: int64

In [14]:
Area_dic = {
    "shiben" : 1123,
    "Tanta" : 788,
    "Cairo" : 9055
}
Area = pd.Series(Area_dic)
Area

shiben    1123
Tanta      788
Cairo     9055
dtype: int64

In [15]:

school_dic = {
    "shiben" : 23,
    "Tanta" : 78,
    "Cairo" : 55
}
school = pd.Series(school_dic)
school

shiben    23
Tanta     78
Cairo     55
dtype: int64

In [16]:
pd.DataFrame({
    "population" : population ,
    "Area" : Area ,
    "school" : school
})

        population  Area  school
shiben        1234  1123      23
Tanta         9876   788      78
Cairo        12345  9055      55

In [17]:
import pandas as pd

In [18]:
path = r'C:\Users\Dr Maha Abdallah\Downloads\customers-10000.csv'
df = pd.read_csv(path)
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,EB54EF1154C3A78,Heather,Callahan,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,2020-08-26,http://www.escobar.org/
1,2,10dAcafEBbA5FcA,Kristina,Ferrell,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/
2,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/
3,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,2020-07-02,https://delacruz-freeman.org/
4,5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,2021-01-17,https://welch.info/
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,DD0caa06ebf217c,Meghan,Cline,Richardson LLC,Petersport,Cote d'Ivoire,001-270-136-4738x419,001-349-692-1755x055,nicolasandrade@bates.info,2022-04-27,http://thomas-ramos.com/
9996,9997,C1C62ff90D0AfED,Jeremiah,Pena,Hodge-Nixon,Briggsport,Namibia,+1-531-494-7645x4844,001-295-324-5502x5411,tracy68@wade.com,2022-01-17,https://www.campbell.com/
9997,9998,2EfAa6Fe435A7DA,Peggy,Key,Vang LLC,West Joyceport,United States Virgin Islands,520.109.2482x26052,+1-602-934-5901x95106,mclaughlinjulia@barnett-dorsey.com,2022-01-13,http://www.george-scott.com/
9998,9999,5dB06C3Fab5CCCb,Evan,Humphrey,Gould Ltd,Camachochester,Niger,001-465-242-9979,001-639-955-2116x751,velazquezjessica@villegas-wilcox.com,2020-04-14,https://www.payne.info/
9999,10000,9903e8fF4D8Ff0F,Melissa,Montgomery,Burns-Holden,Sparkstown,Tunisia,+1-889-682-9490x65400,423.632.2539x98740,ngallagher@martinez.com,2020-06-27,http://nixon.net/

In [19]:
df.head(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,EB54EF1154C3A78,Heather,Callahan,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,2020-08-26,http://www.escobar.org/
1,2,10dAcafEBbA5FcA,Kristina,Ferrell,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/
2,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/
3,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,2020-07-02,https://delacruz-freeman.org/
4,5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,2021-01-17,https://welch.info/

In [20]:
df.tail(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
9995,9996,DD0caa06ebf217c,Meghan,Cline,Richardson LLC,Petersport,Cote d'Ivoire,001-270-136-4738x419,001-349-692-1755x055,nicolasandrade@bates.info,2022-04-27,http://thomas-ramos.com/
9996,9997,C1C62ff90D0AfED,Jeremiah,Pena,Hodge-Nixon,Briggsport,Namibia,+1-531-494-7645x4844,001-295-324-5502x5411,tracy68@wade.com,2022-01-17,https://www.campbell.com/
9997,9998,2EfAa6Fe435A7DA,Peggy,Key,Vang LLC,West Joyceport,United States Virgin Islands,520.109.2482x26052,+1-602-934-5901x95106,mclaughlinjulia@barnett-dorsey.com,2022-01-13,http://www.george-scott.com/
9998,9999,5dB06C3Fab5CCCb,Evan,Humphrey,Gould Ltd,Camachochester,Niger,001-465-242-9979,001-639-955-2116x751,velazquezjessica@villegas-wilcox.com,2020-04-14,https://www.payne.info/
9999,10000,9903e8fF4D8Ff0F,Melissa,Montgomery,Burns-Holden,Sparkstown,Tunisia,+1-889-682-9490x65400,423.632.2539x98740,ngallagher@martinez.com,2020-06-27,http://nixon.net/

In [21]:
df.columns

Index(['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City',
       'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date',
       'Website'],
      dtype='str')

In [22]:
df["Last Name"]

0         Callahan
1          Ferrell
2         Andersen
3            Ponce
4        Mccormick
           ...
9995         Cline
9996          Pena
9997           Key
9998      Humphrey
9999    Montgomery
Name: Last Name, Length: 10000, dtype: str

In [23]:
df["Last Name"][0 : 5]

0     Callahan
1      Ferrell
2     Andersen
3        Ponce
4    Mccormick
Name: Last Name, dtype: str

In [24]:
df.iloc[1:4]

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
1,2,10dAcafEBbA5FcA,Kristina,Ferrell,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/
2,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/
3,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,2020-07-02,https://delacruz-freeman.org/

In [25]:
df.iloc[2,3]

'Andersen'

In [26]:
for index , row in df.iterrows():
    print(index, row["Last Name"])

0 Callahan
1 Ferrell
2 Andersen
3 Ponce
4 Mccormick
5 Lee
6 Hoffman
7 Wiggins
8 Payne
9 Franco
10 Hawkins
11 Shaffer
12 Moran
13 Hammond
14 Blackwell
15 Newton
16 Archer
17 Griffin
18 Valencia
19 Ramsey
20 Meadows
21 Brock
22 Pope
23 Stanton
24 Flynn
25 Williamson
26 Calderon
27 Walton
28 Mack
29 Jacobson
30 Harper
31 Mayer
32 Owens
33 Davies
34 Cruz
35 Hubbard
36 Bennett
37 Hansen
38 Foster
39 Medina
40 Santana
41 Moreno
42 Bush
43 Davenport
44 Terry
45 Esparza
46 Richard
47 Moore
48 Gillespie
49 Lin
50 Thomas
51 Fischer
52 West
53 Morton
54 Guerra
55 Shelton
56 Meza
57 Tapia
58 Powell
59 Irwin
60 Hodge
61 Drake
62 Tran
63 Webster
64 Mcclure
65 Wu
66 Bridges
67 Washington
68 Ayala
69 Hooper
70 Robbins
71 Cobb
72 Salas
73 Long
74 Kemp
75 Horn
76 Spears
77 Ortiz
78 Ortega
79 Cantu
80 Pittman
81 Cowan
82 Chen
83 Stanley
84 Gallegos
85 Pruitt
86 Vaughan
87 Bautista
88 Chase
89 Hurley
90 Huang
91 Cummings
92 Jackson
93 Chapman
94 Cortez
95 Hendrix
96 Buchanan
97 Moore
98 Tanner
99 Sims
100 Strong
101 Mullins
102 Rush
103 Hurst
104 Collier
105 Sanchez
106 Manning
107 Forbes
108 Ryan
109 Short
110 Henry
111 West
112 Gallagher
113 Wiley
114 Merritt
115 Mejia
116 Alvarez
117 Berger
118 Daniel
119 Mueller
120 Middleton
121 Fletcher
122 Wong
123 Brock
124 Petersen
125 Fuller
126 Klein
127 Richards
128 Fitzpatrick
129 Gregory
130 Mckay
131 Rhodes
132 Byrd
133 Miller
134 Marsh
135 Paul
136 Oconnell
137 Bradshaw
138 Chase
139 Crawford
140 Vance
141 Sanford
142 Singleton
143 Sutton
144 Eaton
145 Huff
146 Pollard
147 Hunter
148 Miles
149 May
150 Garza
151 Brown
152 Oconnell
153 Garrett
154 Bender
155 Harrison
156 Fowler
157 Golden
158 Lawson
159 Vaughan
160 Hoover
161 Boyle
162 Noble
163 Molina
164 Christian
165 Estes
166 Myers
167 Barker
168 Huerta
169 Knight
170 Booth
171 Guerra
172 Murillo
173 Lawrence
174 Ewing
175 Pacheco
176 Browning
177 Woods
178 Lopez
179 Small
180 Kirk
181 Arellano
182 Hayden
183 Bullock
184 Leonard
185 Mcfarland
186 Steele
187 Boone
188 Moyer
189 Reese
190 Bullock
191 Paul
192 Cardenas
193 Velez
194 Collins
195 Harper
196 Serrano
197 Robbins
198 Abbott
199 Cantrell
200 Washington
201 Suarez
202 Washington
203 Hamilton
204 Fletcher
205 Morse
206 Pruitt
207 Peterson
208 Pearson
209 Meadows
210 Dickson
211 Shannon
212 Vasquez
213 Oconnell
214 Walker
215 Shah
216 Mitchell
217 Schmidt
218 Simpson
219 Keith
220 Hoffman
221 Tyler
222 Ford
223 Gates
224 Gaines
225 Wilson
226 Jordan
227 Stafford
228 Saunders
229 Barrera
230 Bullock
231 Stuart
232 Lamb
233 Huang
234 Hendricks
235 Ramos
236 Carpenter
237 Whitehead
238 Arnold
239 Lawrence
240 Moran
241 Stephens
242 Hale
243 Lee
244 Savage
245 Duffy
246 Serrano
247 Rosales
248 Arellano
249 Shea
250 Case
251 Horn
252 Cortez
253 Howe
254 Pugh
255 Little
256 Owen
257 Baxter
258 Silva
259 Barnett
260 Chen
261 Hurley
262 Le
263 West
264 Campbell
265 Frye
266 Sanchez
267 Weiss
268 Ferguson
269 Molina
270 Zimmerman
271 Haynes
272 Levine
273 Larson
274 Carr
275 Daniel
276 Garcia
277 Morales
278 Bruce
279 Atkins
280 Huynh
281 Hopkins
282 Booker
283 Lowe
284 Donaldson
285 Morton
286 Mccarty
287 Beasley
288 Yu
289 Stanton
290 Zavala
291 Keith
292 Pace
293 Hall
294 Paul
295 Rowland
296 Woodard
297 Larsen
298 Sawyer
299 Hodges
300 Dominguez
301 Hammond
302 Allison
303 Walters
304 Lara
305 Mendoza
306 Gomez
307 Wagner
308 Davies
309 Navarro
310 Kelly
311 Frost
312 Holden
313 Conrad
314 Fischer
315 Hardy
316 Rios
317 Soto
318 Brown
319 Ingram
320 Bailey
321 Hendrix
322 Armstrong
323 Baxter
324 Washington
325 Haney
326 Park
327 Valencia
328 Green
329 Fisher
330 Clarke
331 Christensen
332 Vincent
333 Burton
334 Moss
335 Cisneros
336 Conner
337 Downs
338 Walsh
339 Daniel
340 Livingston
341 Maldonado
342 Walters
343 Cooke
344 Foster
345 Bradshaw
346 Porter
347 Merritt
348 Barnett
349 Mclaughlin
350 Newton
351 Brennan
352 Simmons
353 Estes
354 Gregory
355 Barnes
356 Chaney
357 Mckenzie
358 Schaefer
359 Patterson
360 Potts
361 Rosario
362 Adams
363 Boyer
364 Bryan
365 Schaefer
366 Perry
367 Morales
368 Hardy
369 Fisher
370 Esparza
371 Mata
372 Golden
373 Yates
374 Wolfe
375 Hendrix
376 Flynn
377 Edwards
378 Villegas
379 Ramsey
380 Zamora
381 Roberson
382 Rhodes
383 Cortez
384 Daugherty
385 Hunt
386 Valencia
387 Quinn
388 Church
389 Livingston
390 Lopez
391 Lang
392 Allison
393 Warren
394 Finley
395 Boyer
396 Avila
397 Nguyen
398 Cardenas
399 Keith
400 Sanford
401 Carney
402 Logan
403 White
404 Shaffer
405 Hester
406 Rivera
407 Bradford
408 Peck
409 Wiggins
410 Clarke
411 Munoz
412 Brennan
413 Baldwin
414 Atkins
415 Gates
416 Swanson
417 Maddox
418 Middleton
419 Hill
420 Robbins
421 Blackwell
422 Byrd
423 Gomez
424 Koch
425 Horton
426 Williams
427 Thompson
428 Rogers
429 Murray
430 Tran
431 Rojas
432 Holt
433 Dixon
434 Patrick
435 Fletcher
436 Carrillo
437 Brady
438 Hancock
439 Maddox
440 Tapia
441 Fry
442 Jensen
443 Hammond
444 Bright
445 Cross
446 Burnett
447 Vincent
448 Pena
449 Harper
450 Crane
451 Steele
452 Snow
453 Cardenas
454 Duffy
455 Dickerson
456 Calderon
457 Charles
458 Mayo
459 Odom
460 Banks
461 Everett
462 Joyce
463 Kim
464 Anthony
465 Ortega
466 Brooks
467 Berger
468 Flores
469 Melton
470 Duffy
471 Andrade
472 Singh
473 Mcclain
474 Harmon
475 Fry
476 Gardner
477 Levy
478 Daniel
479 Mcintyre
480 Thornton
481 Moses
482 Hebert
483 Bolton
484 James
485 Farmer
486 Ali
487 Waller
488 Best
489 Werner
490 Kerr
491 Alvarado
492 Reese
493 Whitehead
494 Tran
495 Barry
496 Palmer
497 Stevens
498 Pugh
499 Boyle
500 Payne
501 Black
502 Holden
503 Castro
504 Burns
505 Jackson
506 Howard
507 Hurst
508 Santiago
509 Ball
510 Flores
511 Hall
512 Adams
513 Bradford
514 Booker
515 Valdez
516 Davis
517 Singh
518 Mcfarland
519 Hansen
520 Boone
521 Hogan
522 Davenport
523 Tapia
524 Hancock
525 Tran
526 Rogers
527 Powers
528 Mcpherson
529 Wagner
530 Ingram
531 Church
532 Leon
533 Fleming
534 Giles
535 Rasmussen
536 Bartlett
537 Haney
538 Kennedy
539 Valdez
540 Dodson
541 Nicholson
542 Dickerson
543 Trevino
544 Bowers
545 Nielsen
546 Scott
547 Dunlap
548 Hardin
549 Lindsey
550 Sloan
551 Schultz
552 Cline
553 Beasley
554 Hancock
555 Blair
556 Moyer
557 Schmitt
558 Singleton
559 Kline
560 Valencia
561 Levine
562 Frye
563 Avila
564 Mullen
565 Fowler
566 Sanford
567 Dalton
568 Kane
569 Estes
570 Benjamin
571 Guerra
572 Tucker
573 Cherry
574 Drake
575 Gutierrez
576 Waters
577 Christensen
578 Pittman
579 Duran
580 Quinn
581 Ware
582 Gaines
583 Shannon
584 Donaldson
585 Pope
586 Farrell
587 Banks
588 Hansen
589 Clayton
590 Allen
591 Valdez
592 Perry
593 Fitzgerald
594 Benitez
595 Daugherty
596 Riley
597 Graham
598 Mcbride
599 Neal
600 Middleton
601 Hutchinson
602 Haas
603 Finley
604 Goodwin
605 Ferguson
606 Rosario
607 Casey
608 Davidson
609 Eaton
610 Conley
611 Lester
612 Palmer
613 Forbes
614 Dunn
615 Wade
616 Mccann
617 George
618 Guerra
619 Mcmillan
620 Barr
621 Dunlap
622 Saunders
623 Riggs
624 Herring
625 Small
626 Holder
627 Stanley
628 Salazar
629 Odonnell
630 Solomon
631 Gilmore
632 Bush
633 Hart
634 Bryan
635 Bartlett
636 Wall
637 Arroyo
638 Choi
639 Villegas
640 Kline
641 Oneill
642 Gonzales
643 Morris
644 Terry
645 Ellison
646 Ortega
647 Hunter
648 Mcknight
649 Brandt
650 Rojas
651 Burton
652 Moss
653 Mullen
654 Hill
655 Hale
656 Schneider
657 Ball
658 Neal
659 Singh
660 Day
661 Huynh
662 Nash
663 Herman
664 Richards
665 Fritz
666 Braun
667 Holmes
668 Barber
669 Rosario
670 Benton
671 Hunt
672 Hayes
673 Hickman
674 Barrett
675 Marsh
676 Soto
677 Turner
678 Atkinson
679 Sellers
680 Ritter
681 Cameron
682 Neal
683 Gibbs
684 Hurley
685 Horn
686 Rice
687 Ochoa
688 Thomas
689 Myers
690 Petersen
691 Tanner
692 Copeland
693 Meyers
694 Arnold
695 Mcknight
696 Tran
697 Pittman
698 Bradshaw
699 Blair
700 Simmons
701 Moran
702 Spence
703 Bridges
704 Solomon
705 Gibson
706 Vargas
707 Brandt
708 Lutz
709 Mcneil
710 Ashley
711 Kerr
712 Whitaker
713 Harrison
714 Hancock
715 Dominguez
716 Logan
717 Pena
718 Valdez
719 Escobar
720 Ballard
721 Shields
722 Logan
723 Strong
724 Dunn
725 Acosta
726 Tran
727 Wu
728 Sullivan
729 Levy
730 Gentry
731 Franklin
732 Kramer
733 Woodard
734 Davila
735 Holmes
736 Galvan
737 Herrera
738 Doyle
739 Snow
740 Brooks
741 Willis
742 Orr
743 Houston
744 Hall
745 Fowler
746 Soto
747 Kim
748 Potts
749 Solis
750 Hunter
751 Elliott
752 Hickman
753 Harrison
754 Lamb
755 Reyes
756 Byrd
757 Macdonald
758 Copeland
759 Lucero
760 Melton
761 Dean
762 Kane
763 Sanford
764 Baldwin
765 Barber
766 Mccall
767 Brock
768 Pruitt
769 Richards
770 Mooney
771 Perez
772 Leblanc
773 Wilkinson
774 Maddox
775 Rosales
776 Hutchinson
777 Stein
778 Meyer
779 Harrington
780 Allison
781 Maddox
782 Bowers
783 Benjamin
784 Cisneros
785 Gibson
786 Stanton
787 Cuevas
788 Griffin
789 May
790 Schmitt
791 Alvarado
792 Travis
793 Bradshaw
794 Costa
795 Kramer
796 Conway
797 Fitzgerald
798 Hahn
799 Boyd
800 Reid
801 David
802 Vaughan
803 Cannon
804 Forbes
805 English
806 Mcconnell
807 Pearson
808 Trevino
809 Glass
810 Stevenson
811 Romero
812 Mcclure
813 Middleton
814 Hunter
815 Moreno
816 Winters
817 Bolton
818 Mcintyre
819 Wilkinson
820 Mayo
821 Giles
822 Hodges
823 Werner
824 Pacheco
825 Richards
826 Velez
827 Price
828 Beltran
829 Sawyer
830 Silva
831 Rowe
832 Hancock
833 Booker
834 Floyd
835 Strong
836 Miller
837 Huynh
838 Boone
839 Marquez
840 Lindsey
841 Mckenzie
842 Stephens
843 Tucker
844 Choi
845 Reyes
846 Norton
847 Arnold
848 Mckay
849 Hampton
850 Todd
851 Phelps
852 Lin
853 Ross
854 Rogers
855 Campos
856 Barr
857 Frederick
858 Chandler
859 Frye
860 Dixon
861 Golden
862 Kennedy
863 Drake
864 Collier
865 Ramos
866 Vaughan
867 White
868 Barrera
869 Goodman
870 Bartlett
871 Summers
872 Bernard
873 Rasmussen
874 Obrien
875 Skinner
876 Cain
877 Valencia
878 Johnston
879 Cobb
880 Spears
881 Ingram
882 Brock
883 Madden
884 Alvarado
885 Salas
886 Wells
887 Duncan
888 Singh
889 Myers
890 Gibson
891 Mora
892 Charles
893 Pace
894 Zamora
895 Williamson
896 Mahoney
897 Rodriguez
898 Skinner
899 Callahan
900 Frank
901 Bowen
902 Becker
903 Rangel
904 Sheppard
905 Wright
906 West
907 Walls
908 Crane
909 Thompson
910 Zimmerman
911 Parker
912 Bass
913 Terrell
914 Cochran
915 Patrick
916 Richard
917 Robertson
918 Petty
919 Mckee
920 Shields
921 Gonzales
922 Solis
923 Preston
924 Cardenas
925 Jefferson
926 Ray
927 Chaney
928 Carter
929 Woods
930 Todd
931 Fletcher
932 Nguyen
933 Cantu
934 Estrada
935 Fuller
936 Turner
937 Thompson
938 Mueller
939 Gentry
940 Haynes
941 Burgess
942 Houston
943 Peters
944 Cox
945 Brown
946 Mills
947 Moses
948 Garrison
949 Chapman
950 Ellis
951 Waller
952 Leblanc
953 Moses
954 Compton
955 Butler
956 Alvarado
957 West
958 Strickland
959 Riggs
960 Klein
961 Foley
962 Knapp
963 Pham
964 Torres
965 Mosley
966 Deleon
967 Rivers
968 Hurley
969 Lozano
970 Stanley
971 Jordan
972 Rice
973 Lowery
974 Gould
975 May
976 Santana
977 Peterson
978 Sutton
979 James
980 Stone
981 Haney
982 Garcia
983 Hendricks
984 Bryan
985 Reid
986 Fitzgerald
987 Booth
988 Reilly
989 Bond
990 Estrada
991 Collier
992 Ramsey
993 Hanna
994 Paul
995 Boyer
996 Montgomery
997 Galloway
998 Cabrera
999 Serrano
1000 Santos
1001 Nielsen
1002 Dougherty
1003 Burns
1004 Glass
1005 Love
1006 Davenport
1007 Copeland
1008 Parrish
1009 Colon
1010 Cline
1011 Houston
1012 Hardy
1013 Gonzalez
1014 Higgins
1015 Cervantes
1016 Levy
1017 Malone
1018 Olson
1019 Valencia
1020 Benitez
1021 Munoz
1022 Ford
1023 Braun
1024 Cuevas
1025 Macdonald
1026 Mccall
1027 Kramer
1028 Barrera
1029 Raymond
1030 Lynch
1031 Pruitt
1032 Steele
1033 Patrick
1034 Sweeney
1035 Cobb
1036 Chavez
1037 Lara
1038 Adkins
1039 Paul
1040 Contreras
1041 Ortiz
1042 Kirby
1043 Durham
1044 Mcbride
1045 Bennett
1046 Kramer
1047 Stokes
1048 Daugherty
1049 Banks
1050 Baird
1051 Sanchez
1052 Kennedy
1053 Cummings
1054 Love
1055 Aguilar
1056 Parker
1057 Owen
1058 Blanchard
1059 Frye
1060 Gallegos
1061 Macias
1062 Oneill
1063 Shelton
1064 Diaz
1065 Lynn
1066 Gay
1067 Black
1068 Holmes
1069 Michael
1070 Pacheco
1071 Medina
1072 Levy
1073 Barnes
1074 Rowland
1075 Suarez
1076 Buck
1077 Mcbride
1078 Lang
1079 Munoz
1080 Powers
1081 Barr
1082 Alvarado
1083 Browning
1084 Oconnell
1085 Pena
1086 Riggs
1087 Holt
1088 Esparza
1089 Bautista
1090 Fisher
1091 Lowery
1092 Turner
1093 Casey
1094 Rubio
1095 Lucero
1096 Mcclure
1097 Long
1098 Hinton
1099 Rasmussen
1100 Curtis
1101 Hoover
1102 Mcbride
1103 Taylor
1104 Figueroa
1105 Bass
1106 Farrell
1107 Allen
1108 Dawson
1109 Cuevas
1110 Jones
1111 Gilbert
1112 Humphrey
1113 Ballard
1114 Hardy
1115 Jennings
1116 Reyes
1117 Mccall
1118 Serrano
1119 Duran
1120 Bush
1121 Flynn
1122 Navarro
1123 Andersen
1124 Soto
1125 Horn
1126 Browning
1127 Figueroa
1128 Rivas
1129 Franco
1130 Howard
1131 Monroe
1132 Haney
1133 Young
1134 Mendoza
1135 Nixon
1136 Kidd
1137 Osborne
1138 Patrick
1139 Erickson
1140 Douglas
1141 Townsend
1142 Ferguson
1143 Tanner
1144 Gilmore
1145 Chaney
1146 Patterson
1147 Gaines
1148 Monroe
1149 Lara
1150 Morrow
1151 Hines
1152 Fitzgerald
1153 Griffith
1154 Pratt
1155 Leach
1156 Kerr
1157 Pratt
1158 Holt
1159 Chan
1160 Braun
1161 Costa
1162 Callahan
1163 Hart
1164 Everett
1165 Gonzalez
1166 Powell
1167 Sherman
1168 Potts
1169 Escobar
1170 Griffin
1171 Carey
1172 Nguyen
1173 Flores
1174 Mendez
1175 Hodges
1176 Mccoy
1177 Hartman
1178 Cohen
1179 Solomon
1180 Velasquez
1181 Zuniga
1182 Lindsey
1183 Bradshaw
1184 Fletcher
1185 Bowman
1186 Bradley
1187 Andrade
1188 Decker
1189 Rush
1190 Patel
1191 Phelps
1192 Castillo
1193 Mcfarland
1194 Bridges
1195 Ortiz
1196 Faulkner
1197 Li
1198 Powers
1199 Riley
1200 Bailey
1201 Riddle
1202 Barron
1203 Manning
1204 Werner
1205 Castillo
1206 Peters
1207 Castro
1208 Beltran
1209 Novak
1210 Ayers
1211 Perez
1212 Sampson
1213 Briggs
1214 Curtis
1215 Powell
1216 Fisher
1217 Johns
1218 Hayden
1219 Richards
1220 Levine
1221 Farmer
1222 Orr
1223 Cervantes
1224 Dougherty
1225 Watkins
1226 Matthews
1227 Dickerson
1228 Hensley
1229 Guerrero
1230 Galvan
1231 Cunningham
1232 Rosales
1233 Escobar
1234 Bell
1235 Hendricks
1236 Dickerson
1237 Chang
1238 Ponce
1239 Sawyer
1240 Nunez
1241 Stein
1242 Garrison
1243 Daniel
1244 Brady
1245 Fry
1246 Good
1247 Ellis
1248 Sampson
1249 Larson
1250 Pittman
1251 Valenzuela
1252 Huynh
1253 Galloway
1254 Barron
1255 Poole
1256 Bartlett
1257 Hanson
1258 Cisneros
1259 Potter
1260 Walton
1261 Mayer
1262 Alvarado
1263 Rush
1264 Nielsen
1265 Reeves
1266 Shah
1267 Andrews
1268 Rojas
1269 Crosby
1270 Avery
1271 Hale
1272 Bernard
1273 Buckley
1274 Bowers
1275 Mcconnell
1276 Richard
1277 Harrington
1278 Mcmahon
1279 Mahoney
1280 Higgins
1281 Hodges
1282 Proctor
1283 Cooley
1284 Rojas
1285 Bean
1286 Mata
1287 Morrison
1288 Pugh
1289 Fritz
1290 Zavala
1291 Spence
1292 Armstrong
1293 Ware
1294 Becker
1295 Koch
1296 Abbott
1297 Myers
1298 Sparks
1299 Frank
1300 Garza
1301 Parsons
1302 Meyers
1303 Clay
1304 Mcneil
1305 Fleming
1306 Soto
1307 Orr
1308 Potter
1309 Stevenson
1310 Kidd
1311 Hudson
1312 Eaton
1313 Odonnell
1314 Anderson
1315 Hardin
1316 Hardy
1317 Chambers
1318 Morton
1319 Orr
1320 Hood
1321 Hanson
1322 Cortez
1323 Taylor
1324 Downs
1325 Mullen
1326 Harding
1327 Morgan
1328 Swanson
1329 Boyd
1330 Daniels
1331 Lutz
1332 Hunter
1333 Harrell
1334 Dunlap
1335 Bentley
1336 Duke
1337 Morse
1338 Herman
1339 Robles
1340 Madden
1341 Pope
1342 Arnold
1343 Stafford
1344 Doyle
1345 Blake
1346 Jordan
1347 York
1348 Reynolds
1349 Delgado
1350 Cantrell
1351 Mendez
1352 Reese
1353 Woods
1354 Landry
1355 Pacheco
1356 Branch
1357 French
1358 Combs
1359 Macias
1360 Mckay
1361 Ellison
1362 Vang
1363 Callahan
1364 Hatfield
1365 Church
1366 Terry
1367 Flynn
1368 Duarte
1369 Osborne
1370 Schneider
1371 Lamb
1372 Jefferson
1373 Alexander
1374 Barry
1375 Salinas
1376 Leon
1377 Charles
1378 Knapp
1379 Atkins
1380 Lawson
1381 Duke
1382 Chan
1383 Larsen
1384 Conway
1385 Williams
1386 Hancock
1387 Hicks
1388 Taylor
1389 Mooney
1390 Orozco
1391 Fry
1392 Molina
1393 Stark
1394 Chapman
1395 Kelly
1396 Tran
1397 Callahan
1398 Wilkerson
1399 Erickson
1400 Braun
1401 Hayden
1402 Gilbert
1403 Esparza
1404 Villarreal
1405 Riggs
1406 Stanley
1407 Montoya
1408 Anthony
1409 Dickson
1410 Wolf
1411 Ballard
1412 Benitez
1413 Cabrera
1414 Arias
1415 Clark
1416 Wolfe
1417 Blackwell
1418 Rocha
1419 Steele
1420 Alvarez
1421 Moss
1422 Perry
1423 Christensen
1424 Cisneros
1425 Cantrell
1426 Kemp
1427 Meza
1428 Heath
1429 Solis
1430 Maldonado
1431 Castillo
1432 Norris
1433 Winters
1434 Lester
1435 Hansen
1436 Richard
1437 Mercado
1438 Farley
1439 Green
1440 Odom
1441 Kemp
1442 Franklin
1443 Mahoney
1444 Vincent
1445 Mcpherson
1446 Riley
1447 Dudley
1448 Skinner
1449 Hancock
1450 Shepherd
1451 Pham
1452 Andersen
1453 Roberson
1454 Booker
1455 Gould
1456 Shelton
1457 Vega
1458 Prince
1459 Bowen
1460 Suarez
1461 Barber
1462 Olsen
1463 Castillo
1464 Thomas
1465 Medina
1466 Wade
1467 Hickman
1468 Lane
1469 Underwood
1470 Chapman
1471 Garner
1472 Barrett
1473 Shah
1474 Baker
1475 Griffith
1476 Bonilla
1477 Maldonado
1478 Hughes
1479 Mcdonald
1480 Mcgee
1481 Glenn
1482 Hines
1483 Sawyer
1484 Sawyer
1485 Williamson
1486 Harmon
1487 Carroll
1488 Bird
1489 Beltran
1490 Mayer
1491 Todd
1492 Garza
1493 Moody
1494 Pennington
1495 May
1496 Carney
1497 Ritter
1498 Wood
1499 Whitney
1500 Dorsey
1501 Hale
1502 Pacheco
1503 Holt
1504 Chase
1505 Hayden
1506 Krueger
1507 Terry
1508 Weber
1509 Young
1510 Thompson
1511 Perkins
1512 Kane
1513 Kelley
1514 Stephenson
1515 Sheppard
1516 Sanchez
1517 Nicholson
1518 Oneal
1519 Carlson
1520 Potter
1521 Barnett
1522 Odom
1523 Swanson
1524 Murillo
1525 Pineda
1526 Savage
1527 Marsh
1528 Parrish
1529 Terrell
1530 Benjamin
1531 Griffith
1532 Adkins
1533 Williamson
1534 Maldonado
1535 Price
1536 Dean
1537 Cooley
1538 Ryan
1539 Fitzgerald
1540 Whitney
1541 Church
1542 Frazier
1543 Yang
1544 Fowler
1545 Garrison
1546 Blackburn
1547 Harris
1548 Hendrix
1549 Parrish
1550 Munoz
1551 Powell
1552 Riddle
1553 Rogers
1554 Serrano
1555 Ewing
1556 Kaufman
1557 Fry
1558 Oconnell
1559 Roberson
1560 Shepard
1561 Shah
1562 Fuller
1563 Martinez
1564 Juarez
1565 Benjamin
1566 Campos
1567 Lutz
1568 Ortega
1569 Shah
1570 Peters
1571 Randall
1572 Drake
1573 Vang
1574 Duran
1575 Garza
1576 Jordan
1577 Cooper
1578 Welch
1579 Cuevas
1580 Braun
1581 Best
1582 Cohen
1583 Pope
1584 Juarez
1585 Robertson
1586 Zamora
1587 Melton
1588 Lane
1589 Solomon
1590 Johns
1591 Farmer
1592 Decker
1593 Morris
1594 Irwin
1595 Baldwin
1596 Hooper
1597 Estes
1598 Prince
1599 Adams
1600 Tanner
1601 Bush
1602 Stevenson
1603 Mejia
1604 Chung
1605 Roth
1606 Reyes
1607 Mack
1608 Glass
1609 Henry
1610 Mcpherson
1611 Cohen
1612 Hines
1613 Vance
1614 Berger
1615 Vang
1616 Reese
1617 Fuentes
1618 Harrell
1619 Porter
1620 Figueroa
1621 Bullock
1622 Cervantes
1623 Goodwin
1624 Frazier
1625 Wilkinson
1626 Valenzuela
1627 Casey
1628 Short
1629 Griffin
1630 Pham
1631 Miranda
1632 Deleon
1633 Lam
1634 Kirk
1635 Hendricks
1636 Gallagher
1637 Goodman
1638 Benton
1639 Hunt
1640 Cunningham
1641 Glenn
1642 Moon
1643 Orozco
1644 Chen
1645 Stanton
1646 Mcpherson
1647 Butler
1648 Cuevas
1649 Cobb
1650 Simpson
1651 Morales
1652 Mcmahon
1653 Mccormick
1654 Oconnell
1655 Kaufman
1656 Nunez
1657 Singh
1658 Patrick
1659 Eaton
1660 Good
1661 Pruitt
1662 Mann
1663 Dixon
1664 Hughes
1665 Wheeler
1666 Aguilar
1667 Clayton
1668 French
1669 Walsh
1670 Mckenzie
1671 Garrison
1672 Hendrix
1673 Cuevas
1674 Crawford
1675 Galloway
1676 Ortega
1677 Potter
1678 Singleton
1679 Espinoza
1680 Scott
1681 Walls
1682 Ibarra
1683 Nicholson
1684 Mccoy
1685 Kelley
1686 Duarte
1687 Obrien
1688 Maxwell
1689 Davis
1690 Stein
1691 Carney
1692 Rollins
1693 Rocha
1694 Banks
1695 Woodward
1696 Hudson
1697 Moses
1698 Merritt
1699 Rollins
1700 Townsend
1701 Madden
1702 Harrell
1703 Schwartz
1704 Huynh
1705 Bates
1706 Davenport
1707 Stuart
1708 Kidd
1709 Hampton
1710 Jimenez
1711 Nixon
1712 Hardin
1713 Sosa
1714 Bennett
1715 Mcclure
1716 Lawson
1717 Harper
1718 Horn
1719 Conway
1720 Chung
1721 Serrano
1722 Reilly
1723 Li
1724 Hampton
1725 Ramsey
1726 Spears
1727 Novak
1728 Wilkerson
1729 Clark
1730 Barron
1731 Mccann
1732 Mendoza
1733 Alvarez
1734 Harmon
1735 Sullivan
1736 Gillespie
1737 Campbell
1738 Foley
1739 Barron

In [27]:
df.loc[df ["Country"] == "Andorra"]

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
1,2,10dAcafEBbA5FcA,Kristina,Ferrell,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/
696,697,Da63bffb10feFc2,Zachary,Tran,"Shepherd, Greer and Murphy",Kimberlyburgh,Andorra,831.331.8338x3219,145.151.4483x888,lstrong@aguirre.org,2021-02-10,http://parks.biz/
874,875,Ed3DDEE0De1b769,Becky,Obrien,"Dunlap, Page and Duke",North Billfort,Andorra,256.124.9882,+1-503-703-0457x21281,wileygordon@salinas.com,2020-05-02,https://merritt.com/
1149,1150,80299d79EBDdfEa,Sierra,Lara,Salinas PLC,North Donaldborough,Andorra,+1-850-697-1448x913,+1-335-445-3330x8126,junderwood@thompson.info,2022-01-05,http://berg.org/
1202,1203,29f0D7dBdef8b72,Sean,Barron,Rowland-Chapman,Ralphchester,Andorra,001-991-926-7565x4855,(433)527-0315x988,copelandkirk@gomez-forbes.com,2020-08-06,https://www.henry.com/
1624,1625,a35FBCA4cf322cB,Laurie,Frazier,"Gates, Tran and Simpson",Port Stuartfort,Andorra,+1-238-958-7740,(275)989-2919x948,mccarthyalicia@scott.info,2021-10-26,http://www.summers.com/
1652,1653,33109D4a0173C75,Kristopher,Mcmahon,"Clay, Hodge and Andrade",Lake Charlesside,Andorra,001-899-611-5856x118,001-632-770-8961,kyliemartinez@webster.net,2020-01-18,http://greene.biz/
1748,1749,56dE084ff34F362,Alejandra,Braun,Ferrell-Whitney,Jeffersonland,Andorra,(949)514-4961,+1-939-206-8414x504,dominique23@larson-macias.info,2021-10-23,https://daugherty.com/
1821,1822,aB5C6b1Fd82bF1f,Darren,Huynh,"Howard, Frye and Neal",Jimenezland,Andorra,+1-095-864-3551x4775,+1-119-925-6997x97182,kariarnold@valentine-underwood.net,2021-10-05,http://lester.info/
2197,2198,81d3bA3fC7CDA8C,James,Holt,Kent and Sons,Suttonland,Andorra,1800337906,951-006-9287x937,marisa33@richardson-tate.com,2021-01-06,http://www.jackson.com/
2367,2368,CaF3696521b1Ec9,Lonnie,Weiss,"Alvarez, Harper and Haynes",Galvanstad,Andorra,+1-278-463-7269x9152,182-504-7895,nichole69@hodge-boyd.biz,2021-03-22,https://bates.com/
2459,2460,75eff8a1c363EAe,Xavier,Gordon,Woods PLC,Navarrobury,Andorra,460-020-7429x110,(400)001-5850x0976,rebeccaestrada@mooney-blackburn.net,2021-07-24,https://www.ford-pruitt.com/
2658,2659,900810eC061e685,Theresa,Wilkins,Mendoza-Miranda,Oliviamouth,Andorra,(360)869-2013,001-220-004-1833x7124,lorraine16@blankenship.com,2020-07-12,https://www.pruitt.com/
2885,2886,Ae692a12C8611cf,Brenda,Harrington,Boyle-Kent,Port Dianaberg,Andorra,226.236.5485x721,397-030-1787,mindybullock@huffman.biz,2020-09-22,http://mcpherson.com/
2991,2992,61c0EcFBbFD8Aad,Isaiah,Mathis,Russell PLC,Alfredland,Andorra,613.434.8276,+1-153-744-3171,kirk31@benton.biz,2021-07-05,http://wiggins.net/
3184,3185,592dABd35E820b8,Pamela,Bruce,Guerrero-Whitney,Annettemouth,Andorra,+1-400-560-4545x676,386-010-1143,latoyamendoza@macias.com,2020-02-04,http://barton-schneider.com/
3531,3532,18FBb3A38dfCa58,Stefanie,Shannon,"Wilkinson, May and Santos",North Stephanieburgh,Andorra,377.733.1183,310-732-6065,blakele@sloan.com,2020-12-27,http://hendrix-pearson.net/
3618,3619,5F1ccD0682bFFfB,Amanda,Hawkins,Golden-Gates,East Kimberly,Andorra,882.976.9157x210,(571)663-5509,eugene62@rodgers.com,2021-10-28,https://www.cross-graham.com/
3642,3643,6cA9b2cba4FFf1b,Kaitlyn,Berger,Hahn LLC,East Drewton,Andorra,508-795-4892,135-800-6180x6572,qkline@gamble-pena.biz,2020-03-06,https://www.hoover.com/
3648,3649,AB78B6C32E16E6e,Duane,Sosa,Martin LLC,New Jay,Andorra,(551)354-5347x543,+1-022-846-8813x4354,bullockshari@roth.info,2021-08-20,http://chandler-alexander.info/
3844,3845,BCbaa2fAaB68E65,Tom,Campbell,Watson Ltd,New Alfredburgh,Andorra,+1-258-330-1652x0449,338-755-8976x897,rosshaas@avila.com,2020-05-17,http://www.sawyer.com/
3850,3851,CBdD876cE0A1Feb,Clinton,Castro,Atkinson-Bright,Hardingmouth,Andorra,782-177-0876,010-453-1373x9116,zbush@henson-blake.info,2021-04-22,https://davies-holder.com/
3925,3926,7d899C243b2DEEE,Caitlyn,Nichols,"Huynh, Decker and Herman",Lake Todd,Andorra,249.283.5913x750,+1-236-371-8929x7211,harold50@pollard.biz,2022-02-27,https://www.payne-humphrey.info/
4039,4040,4E80b48Ae2f5493,Bridget,Trevino,Krause-Stanley,Lake Aimeeside,Andorra,(468)936-1314,3381283810,kingerica@beck.com,2021-07-26,https://howard.com/
4077,4078,F25CebAAB7Ffd0C,Melissa,Elliott,Montgomery-Herring,East Herbertville,Andorra,+1-579-347-0457,934.457.3508x865,elijahzhang@adkins.com,2021-09-17,http://solis.com/
4553,4554,0Ca7c71e62c9De0,Darius,Wolf,"Hickman, Bartlett and Sparks",Stevensmouth,Andorra,(541)395-1925,952.426.2780x40249,frederick37@bean.com,2021-09-23,https://www.poole.biz/
4684,4685,2f782F314b00AaB,Ian,Rubio,Marsh PLC,Theodoreshire,Andorra,198.618.1658x1161,740.331.7592x4093,jason52@mccarthy.info,2020-09-21,https://blackwell-delacruz.com/
4941,4942,fFED50f5A906AC7,Mary,Newton,"Huber, Gonzales and Swanson",Pettyberg,Andorra,755-070-5626,376-966-0872x331,fduffy@bonilla.info,2021-05-03,http://orozco.org/
4973,4974,e7E171c943aca38,Shari,York,Hayes-Davenport,North Mark,Andorra,+1-006-563-7378x192,+1-607-230-9580,ngoodman@parks.com,2020-01-10,http://pruitt.com/
5062,5063,dB1E7f047Abe28C,Kristen,Cunningham,Woodard LLC,Ricardomouth,Andorra,001-412-606-8930,001-018-728-0386x314,jdavis@rodgers.info,2022-03-12,http://wheeler-shepherd.biz/
5332,5333,ec2Ac817AE2bC97,Gavin,Pugh,"Richards, Johnson and Briggs",Crystalchester,Andorra,694.935.8037x98571,+1-811-826-2210x66758,connerjaclyn@neal.com,2020-02-19,http://www.silva.net/
5356,5357,fA6f2A6b1bc2c0B,James,Keith,Mays-Murray,Rangelview,Andorra,5282748394,+1-534-128-9357x931,arianarichards@vargas-bartlett.com,2020-02-27,http://www.fox.info/
5666,5667,6FC032EA06AA72C,Jeanne,Lawson,Lin-Gill,Virginiastad,Andorra,(762)827-7364x6340,4969181501,richarddickerson@crosby-lawrence.com,2020-09-21,http://www.davidson-powers.biz/
5817,5818,31bE437Cb756CF5,Mikayla,Tucker,"Vance, Rice and Kim",Kurtberg,Andorra,697-549-8712x532,216.940.9409,lucaspratt@pennington.com,2020-01-18,http://gonzales.com/
5889,5890,7d4b0cB7f1b07b0,Ronnie,Watkins,Russo-Hines,South Ralphside,Andorra,412.668.0132,8599205667,amandawaters@bentley.net,2020-06-24,http://yoder.com/
6023,6024,c4fb76EC1FaDAc2,Travis,Duran,Rice Group,New Daltonside,Andorra,575.678.2940,+1-744-627-9529x8957,ralph79@li-gordon.com,2020-03-07,http://www.diaz.biz/
6126,6127,75b6e8F85128EbC,Darren,Becker,Coffey and Sons,Carneyborough,Andorra,001-104-682-1003x2035,1888011391,camposrachel@savage-gaines.com,2021-06-28,http://www.ballard-knox.org/
6328,6329,55aEDeD91Ed4Ed9,Nathaniel,Bonilla,Eaton-Decker,East Theodore,Andorra,(374)713-2461x102,+1-149-842-5717x7207,crawforddanielle@garner.com,2020-04-18,https://www.robbins.com/
6557,6558,A0ae6C4182FaDbA,Mason,Little,"Krueger, Holt and Dawson",East Gordon,Andorra,606.819.3447x624,(645)180-8613x20901,elliottrose@lindsey.com,2021-01-19,https://torres.org/
6727,6728,025d9B97DEaB5cf,Kelsey,Strickland,Ruiz Inc,Marshfort,Andorra,001-697-158-3924x915,455.626.8086x437,cheyenneguerra@burke.com,2020-10-23,http://robertson.com/
7109,7110,8cc8cBE18EaaC05,Caroline,Dunlap,"Bailey, Anderson and Porter",Joview,Andorra,(656)891-0080x410,001-306-014-8564x977,sonia95@bartlett-macias.net,2020-04-24,https://hubbard-crawford.com/
7271,7272,3dBfebafCB5831d,Peggy,Stein,"Mathis, Dennis and Franco",South Lonnie,Andorra,(445)620-7998x502,(687)723-5962,prestonjustin@mcintyre.info,2021-03-25,http://lara.com/
7293,7294,ad4Aedd7EFDd55d,Caitlyn,Mccarty,"Gonzales, Mann and Fernandez",Timothyfort,Andorra,011.787.0580x31630,470-046-7935,shannon72@mahoney-stark.com,2021-06-11,http://cohen.net/
7674,7675,FFafF1b0D4b34fc,Kristen,Phelps,"Gray, Vance and Randall",Sophiaport,Andorra,(108)034-3857x87681,298-741-7661x3743,deannaaguirre@andrews.com,2020-01-29,https://www.greene-gray.biz/
7688,7689,D54CEcdcF90Db6C,Sabrina,Macias,Carroll Ltd,New Kari,Andorra,492-513-0805,408-300-8853,goulddevon@ayers.com,2021-08-28,https://www.benton.com/
7995,7996,c80FE6FfBAfDc6b,Karla,Huang,Daugherty LLC,North Xaviermouth,Andorra,220-457-7567x55730,(160)483-6452,catherinerocha@frederick-cannon.com,2021-10-15,https://ramsey-duncan.com/
8071,8072,A66E51C900A6EC2,Jack,Dawson,Houston PLC,Port Diamond,Andorra,+1-015-167-4824x918,(883)966-6049,kaylapark@monroe-orozco.net,2020-09-26,http://murphy.com/
8422,8423,ddF2f1BdE2FA583,Tim,French,Paul-Cantu,Lake Rileyshire,Andorra,(281)531-6595x95730,+1-808-496-6973x6374,gavin23@mora.info,2020-05-13,http://www.flynn-robinson.com/
8453,8454,7C8b54b0bEC3A0d,Kristine,Cabrera,Davis Inc,New Gracefort,Andorra,005.358.5484,(888)445-7752x784,wulatasha@dodson-ingram.com,2020-01-08,https://www.brandt.com/
8862,8863,3fdf5C6a55CC104,Gabriel,Carey,"Manning, Lutz and Cabrera",North Natasha,Andorra,070-494-8581x988,001-886-029-0533x3904,bonnie87@vaughan.com,2020-01-28,http://www.simpson-horn.biz/
8887,8888,FF955b02C1773E7,Janet,Kemp,Acevedo-Turner,North Craig,Andorra,001-665-529-1162x9948,503.922.4833x6118,humphreydevon@spence.net,2021-03-25,https://www.leach-cain.com/
8931,8932,e881951249CcF03,Cassidy,Ramos,Patel LLC,Port Leeville,Andorra,+1-104-606-5003x467,001-997-464-5557,cdickson@brooks.info,2021-11-23,https://www.vasquez-bishop.com/
9025,9026,277Fd24a2adCcAC,Helen,Walters,Montes and Sons,Pageberg,Andorra,001-824-779-6337x989,(957)716-1224,bensonjonathan@adkins.com,2021-09-06,https://www.dalton.com/
9646,9647,b9bBeAeeab8d9F1,Tina,Lowery,"Love, Simpson and Le",Zhangmouth,Andorra,(070)527-7533,(970)645-3659,lindsay06@ho-quinn.com,2020-12-09,https://www.rodriguez.com/

In [28]:
df.describe()

             Index
count  10000.00000
mean    5000.50000
std     2886.89568
min        1.00000
25%     2500.75000
50%     5000.50000
75%     7500.25000
max    10000.00000

In [29]:
df.sort_values("Last Name", ascending = False)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
5771,5772,9eBD2acaCEb7b96,Tami,Zuniga,Small-Lucero,West Bryceport,Lebanon,977-920-0578,590-505-3466x53710,wrightkaitlyn@blanchard.info,2021-08-15,https://www.andrade.com/
5755,5756,1FfeEeE3cCE7ccC,Rebecca,Zuniga,Harris LLC,New Holly,Ecuador,003-893-4550,119.316.3873,hendrixkirk@kaiser-barrera.com,2022-02-21,https://schultz.com/
5320,5321,a4E042a4C2B9B3c,Ana,Zuniga,"Bray, Bradford and Hart",New Tyrone,Gambia,425-885-6023x61517,461-175-8270,ronnie08@oliver.com,2021-10-11,http://rollins-young.com/
2583,2584,c3928aAEf93beA7,Perry,Zuniga,Lawrence-Gay,West Valerieland,Belgium,829-415-0057x08290,(574)431-5896x462,brettruiz@rivera-moss.com,2020-06-15,http://novak.com/
1181,1182,6FfDBdaB1Ff440C,Garrett,Zuniga,Mccarty Ltd,Tracytown,Colombia,689.851.6741,555.099.1720,manuelgeorge@hogan.com,2021-05-03,https://www.webster.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
4828,4829,2DD738e7980FBcE,Alec,Abbott,"Ali, Dalton and Mcknight",Logantown,Rwanda,239.375.7512x598,001-701-638-5003x20650,benderlogan@sexton.com,2020-07-03,https://edwards-flowers.info/
1296,1297,ABCFefFaDAc5F2C,Judith,Abbott,Potter-Haney,Lake Evanberg,San Marino,(803)522-0695,8758726874,alyssajuarez@villanueva.com,2020-04-14,https://gates.com/
4544,4545,8a9a10BD9D46b9A,Felicia,Abbott,Wood-Hinton,North Trevorbury,New Zealand,526.367.2552,+1-375-609-2802x5394,tarajones@rios-humphrey.com,2021-07-07,http://www.douglas.info/
198,199,8A96EECfBD1E182,Robyn,Abbott,"Dodson, Weaver and Barajas",Jodiberg,Somalia,001-158-488-8157,(812)515-3121x0742,breanna32@mayer.net,2020-12-31,https://www.jordan-phelps.org/
6556,6557,BedfbB8AEADF1D5,Jimmy,Abbott,Black Ltd,New Veronicaside,Indonesia,485.570.2703,951-656-8620x96343,zachary01@anderson-forbes.com,2020-01-10,https://www.everett.com/

In [30]:
df.sort_values(["First Name" ,"Last Name"], ascending = True)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
9922,9923,196DcfDd1ABDeCa,Aaron,Berg,"Wells, Dodson and Rhodes",Lake Gerald,Mozambique,+1-022-635-2617,(038)321-0452,fmedina@kramer-munoz.biz,2020-10-16,http://aguilar.biz/
995,996,a0e3B57D14C2F30,Aaron,Boyer,Burnett-Hinton,South Traci,Barbados,001-795-383-7996,531-635-2300x551,rivaseric@le.com,2021-04-29,http://www.tyler.com/
1647,1648,60BCf0CbBe6b27D,Aaron,Butler,"Robertson, Wise and Love",Houstonburgh,Iran,2192841211,001-222-324-9995x154,cindy82@shaw-saunders.biz,2021-01-15,http://www.fischer-walters.net/
9888,9889,602fC0BCBCDfC7F,Aaron,Campbell,Cline Inc,Port Meaganville,Solomon Islands,286-813-9314,001-607-608-4122x08545,yfarmer@rocha.com,2020-12-25,https://ballard-brooks.info/
9142,9143,C55290972eAFA23,Aaron,Cooke,Ochoa Ltd,Sethside,Marshall Islands,734.289.4618,977.606.7226,tmooney@ferrell.net,2020-09-18,http://www.diaz.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
1863,1864,49FB80BFa60a782,Zoe,Pope,Campos-Clark,New Aaronstad,Ethiopia,(426)153-7018,(176)240-3916x303,tabithahoffman@hudson-berger.com,2021-03-16,https://www.norris.com/
1031,1032,e9bC7F967aDEdbc,Zoe,Pruitt,Simon and Sons,Stevensonton,British Virgin Islands,001-094-235-8186x2281,885-281-9408,latoya01@avery.biz,2020-05-17,http://www.whitaker.com/
431,432,BceA40c37Afe437,Zoe,Rojas,"Browning, Hayes and Barber",Port Glen,United Arab Emirates,001-410-263-1855x0930,+1-980-846-5317,lynnkelli@kirk-bell.org,2020-05-14,https://www.cantrell-taylor.com/
907,908,ba09d8cDfF0eCf9,Zoe,Walls,"Guerra, Reese and Banks",New Clayton,Nepal,531.363.4341,551.279.5477,boylerenee@cruz.com,2021-03-14,https://www.lang-sloan.com/
2306,2307,55ccE335EaAD335,Zoe,Walsh,Hughes-Steele,Lake Devin,United States of America,5425875834,+1-293-673-7840x39730,alex34@barajas.com,2021-11-08,http://ramos-chandler.org/

In [31]:
df.sort_values(["First Name" ,"Last Name"], ascending = [1,0])

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
8184,8185,Dfb02CB8A5cc89f,Aaron,Tucker,"Trujillo, Kemp and Perkins",Port Sheri,Honduras,774-817-3017,+1-799-404-4553x5122,sherri62@everett-sellers.com,2020-10-01,http://kennedy-mathis.com/
7300,7301,9B1d815c9eac9BB,Aaron,Spencer,Cochran Inc,Shanemouth,Sudan,+1-709-843-6595,678.168.4336x3580,marc79@dyer.net,2021-05-02,http://kaiser.biz/
9693,9694,DfEcb07E5Eef1eC,Aaron,Simpson,Cooley Inc,East Jeremiah,Mauritania,126.707.5199x465,+1-541-486-5690x96696,callahanvanessa@garner-daniel.biz,2020-05-04,https://hendricks-davenport.net/
6545,6546,e9afebccEFCdDc3,Aaron,Pena,"Pollard, Michael and Powell",Port Gavinville,Angola,001-177-689-2075x4203,174.951.0383x2871,yvettewalters@arias.net,2020-08-16,http://www.wilkinson.com/
6914,6915,0dAEF35b5cCAa82,Aaron,Ortiz,"Gill, Roman and Blair",West Bradleyberg,Vanuatu,489-652-6564x3529,+1-694-510-8865x85848,jenniferleon@santos-atkinson.biz,2020-07-19,https://simon-hendricks.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
6255,6256,A9aBbA57AF55c4c,Zoe,Pittman,Crane-Wilkerson,Lake Martin,Niue,608.366.4980,301-160-9334x51469,wigginskerry@lucero.com,2021-01-09,http://www.curry.com/
9776,9777,531dE686fFE5b7b,Zoe,Nicholson,Gillespie-Pittman,New Jodyshire,Yemen,(033)208-5901,603-862-3454,morgan59@patrick.com,2020-02-17,http://calhoun-frye.org/
4722,4723,3aEBCDc0BF274AC,Zoe,Liu,Ellison-Dalton,South Mallory,Austria,583.879.2194x4421,(726)031-5434,vcoleman@mcgee.biz,2021-08-21,http://floyd.com/
5805,5806,5546c08f8E23d8c,Zoe,Hanna,Lam-Lin,West Stacie,Oman,(926)764-9929,(509)727-4215x375,bkerr@barry-bender.org,2021-10-11,https://www.watts.org/
7873,7874,5fcb4b2EAb8A38c,Zoe,Cochran,Harrington Ltd,New Alexisburgh,Tuvalu,308.604.9871,669.993.2856x91657,leonardcalhoun@edwards.biz,2022-02-19,http://velasquez.com/

In [32]:
df. to_excel("customers.xlsx", index = False)

In [38]:
df.loc[(df['City'] == 'Petersport') & (df['Country'] == 'Norway')]

Empty DataFrame
Columns: [Index, Customer Id, First Name, Last Name, Company, City, Country, Phone 1, Phone 2, Email, Subscription Date, Website]
Index: []

In [39]:
df.loc[(df['City'] == 'Petersport') | (df['Country'] == 'Norway')]

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,EB54EF1154C3A78,Heather,Callahan,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,2020-08-26,http://www.escobar.org/
233,234,bA3c7355abEB0Aa,Danielle,Huang,"Bailey, Dorsey and Tanner",Port Robert,Norway,4899460466,(309)944-0313,ericksoncheyenne@taylor.com,2020-10-09,https://harris-houston.biz/
293,294,78ac17Cc0E0b444,Danny,Hall,"Coleman, Berg and Larsen",Harrellland,Norway,(937)866-9688x17423,001-778-967-6161x67221,regina78@sampson.net,2021-11-13,https://www.harding.com/
313,314,E44e636cfE26CfB,Maria,Conrad,"Blackwell, Torres and Solomon",Port Ricardomouth,Norway,(899)628-5978,7821216654,gabriel57@spence-thompson.com,2021-11-15,https://www.horn.biz/
383,384,8efE4D4084590A0,Kristi,Cortez,Holder PLC,West Connor,Norway,+1-700-943-8756,(845)221-2397x51427,evelyn41@stanton.net,2022-03-25,http://www.day.com/
420,421,68fbb98f6EbD971,Jack,Robbins,"Choi, Galloway and Fox",Kevinbury,Norway,001-084-704-0454x28664,330.200.8023,haasderrick@ortega-kirk.org,2020-12-02,http://farrell.com/
480,481,d3fF4F1DceACA2D,Christian,Thornton,"Duffy, Castro and Yates",Port Mariostad,Norway,001-037-597-5406,5445268667,gschultz@rollins.com,2020-10-21,https://walter-yates.com/
662,663,45fAcb9b399d894,Andres,Nash,Baldwin PLC,Leviborough,Norway,1787227957,0920114892,jon73@glenn.info,2020-08-25,http://www.morrow.info/
1577,1578,23a1CeD8A626af7,Traci,Cooper,Mcneil-Rose,Karinahaven,Norway,587-562-4038,+1-131-774-0910x143,gloverjeffery@hart.com,2020-12-31,http://www.jordan.com/
1862,1863,7d60D2dDF121acd,Cathy,Jarvis,"Cain, Roman and Pruitt",South Caseyhaven,Norway,+1-044-510-4797x01649,(175)257-8958,miguel55@zimmerman-wong.org,2020-10-13,http://www.mcconnell.com/
1961,1962,3c4A0F6eC172711,Denise,Medina,Singh Ltd,Nicolasbury,Norway,343-029-3561x287,+1-183-867-2005x8687,greggcortez@simpson.info,2022-03-05,https://www.montoya.com/
2127,2128,0FE8eA68A3E2D0f,Patrick,Ray,"Chambers, Mcguire and Obrien",Schultzton,Norway,425-835-8660,580.657.0349x57101,wyatt03@keller.com,2020-02-29,http://hays.com/
2208,2209,F5f264c481eaE1d,Morgan,Robles,Jarvis-Fox,Port Martin,Norway,001-046-462-6677x29915,001-090-971-4902x519,ritapage@webb.com,2020-06-05,https://www.munoz.info/
2260,2261,fA5FF5fbE098ea7,Randy,Rivas,Hurst-Hatfield,North Duaneport,Norway,+1-297-625-1797x302,(559)493-2694x331,andrewyoder@powers.com,2020-01-18,http://www.christian-bruce.net/
2406,2407,eF265Ffe5F32251,Darin,Frye,Barron PLC,Cunninghamburgh,Norway,137-447-1793,(540)399-2312,anna44@eaton-ferrell.com,2020-02-04,http://www.bruce-lin.biz/
2635,2636,A6acfb993EF51cd,Donna,Tyler,Burton-Knapp,Carterside,Norway,844.222.3339,(361)193-5259,qmercer@fitzgerald.org,2021-01-15,https://www.leach-schneider.biz/
3220,3221,CC9B6713dc46eA7,Jerry,Howard,Cain-Chavez,East Erica,Norway,600.564.6533x789,683.517.7956x324,leroyvilla@peck.com,2021-05-22,http://vazquez-dudley.com/
3233,3234,2141FcDE042dFdd,Suzanne,Vasquez,"Hester, Shah and Wilkins",South Martha,Norway,821-718-2287x85602,(728)645-2908x90115,ashleypowell@howe.com,2020-02-21,https://herrera.com/
3345,3346,baC023214718FFB,Melvin,Rodgers,Kemp-Rogers,Cannonport,Norway,866-086-4049x45259,001-907-654-7318x51848,trivas@jarvis.info,2020-06-07,http://mejia.com/
3382,3383,eDACCb9ecaA5E73,Stefanie,Castillo,Owens Group,Hardingfort,Norway,232.529.8173,949.536.7015,eyork@velez-valentine.info,2020-11-05,http://shannon-summers.com/
3393,3394,f459C4b155702B9,Hailey,Salinas,Mueller Group,Elainefurt,Norway,505.216.5358x0437,178.322.7872x85042,psellers@gaines.com,2021-10-04,https://allen.com/
3966,3967,Fd3e45dA3E9f46B,Glen,Pittman,Brown-Hensley,West Tashaborough,Norway,+1-528-305-4978x5200,824-328-7168x29966,losborn@rhodes.com,2022-04-19,http://valencia-hunter.net/
4015,4016,ADDAf477e64FAFE,Lydia,Franco,"Morse, Skinner and Russo",Lake Gabriella,Norway,(589)348-4544x04244,001-036-271-5681x156,parrishjaime@weiss-foley.net,2022-04-10,https://cherry.biz/
4233,4234,17eE17eDEBDADac,Perry,Armstrong,Moss Ltd,South Felicia,Norway,(307)657-3746x9076,001-358-599-3819x32948,garrettmiguel@schroeder-moon.org,2021-04-09,https://www.tapia.com/
4339,4340,2360d3b5761E243,Jamie,Mathis,Evans Group,Mosleybury,Norway,121.980.8697,(995)980-2503x48136,juanroy@leblanc-zhang.biz,2021-03-19,http://owens.com/
4569,4570,aeac9CC0978C8ce,Wayne,Jacobs,Cobb PLC,South Wendy,Norway,+1-894-918-7667x61718,373.397.5516,phillipsanford@good.com,2020-03-15,http://pruitt-hurst.com/
4591,4592,2DaB9ABBa4Ca31c,Krista,Moran,"Hughes, Hayes and Hopkins",New Alvin,Norway,762.964.8815x57206,+1-886-963-1627x92095,rubenperry@klein.com,2021-11-24,http://www.estrada-hall.com/
4672,4673,da5fB0c7F3d3b0A,Matthew,White,Vasquez-Fleming,North Ianbury,Norway,001-009-592-2197x7672,(212)276-7240,cwatkins@gross.com,2021-04-25,http://www.downs-travis.com/
4764,4765,C1af618aaBD782B,Cory,Hunter,Roach Ltd,East Christiefurt,Norway,+1-340-869-8950x9018,001-524-240-8840x059,frederick91@lucero.com,2020-05-20,http://www.cantrell.com/
4944,4945,C0a64b1b6ecFC1b,Savannah,Garcia,Sosa Inc,Kendraton,Norway,007-066-9574x8716,655.061.2342x313,darin04@graves.info,2021-11-07,http://www.kent.biz/
4970,4971,1a7EFe1f12FAe1d,Mariah,Cooper,Santana-Mckenzie,Port Monica,Norway,058.336.3926,7473587564,russellcallahan@barr.com,2021-03-25,https://www.wu-villarreal.com/
5923,5924,055A0EDa34c8Dec,Erica,Donovan,Hatfield-Collins,South Dominic,Norway,857.650.1466,622.571.8737,breanna24@house-mcconnell.com,2020-02-20,http://www.oconnor.com/
6142,6143,fDC137dec49cC67,Wanda,Hughes,Cisneros Inc,Clintonburgh,Norway,726.668.5763,001-677-940-0801x155,daughertymaureen@french-hines.com,2021-06-30,http://key.biz/
6360,6361,bCAC97727C145d1,Kylie,Bartlett,Pham-Valencia,Grimesborough,Norway,166-006-0264x6742,(139)816-4968x2957,mccarthyselena@everett.com,2020-04-08,http://www.merritt-valentine.info/
6413,6414,Cd1Ecacaf6976d5,Hailey,Carney,Tate-Mooney,Tristanland,Norway,001-847-925-1594x9655,307-422-3807x02295,tommyshelton@potts.org,2022-04-02,https://nielsen.biz/
6804,6805,DAeBA87Fa32A36D,Bethany,Weaver,Hebert Inc,Pricemouth,Norway,011-580-0679,(313)806-9611,freemanmelody@gonzalez-hunt.org,2020-12-05,http://www.lindsey.biz/
6997,6998,BecDD3D19b302a2,Shelia,Daniels,"Ritter, Levy and Schmitt",West Ashley,Norway,001-427-693-1096x76506,720-451-3689,alyssastanley@holden.com,2021-03-12,https://www.mendez-mcintyre.org/
7267,7268,AFbE63b72452168,Cody,Krueger,"Day, Galvan and Juarez",West Jodi,Norway,581.887.1294,+1-930-790-5832x185,kirkmoyer@deleon.info,2021-08-26,http://ellis-mann.com/
7472,7473,e04CA67fAB6193b,Glenda,Ibarra,Morrison Ltd,Lake Sharimouth,Norway,755.248.4276,4406028739,yoderkaitlyn@simon-hays.biz,2021-10-11,http://www.underwood.biz/
7604,7605,E889FC28FBf04d3,Margaret,Martin,"Johns, Pittman and Spencer",Cervantesport,Norway,494-137-3613,001-160-736-1785x5236,amber22@navarro.net,2021-11-22,http://gonzalez-cox.com/
7669,7670,25AA85EefA355CA,Katherine,Bond,"Cochran, Strickland and Hobbs",Davidshire,Norway,001-309-984-6582x495,(406)994-5478x39344,charlesbryant@vaughn-osborne.org,2020-09-06,http://www.villarreal.com/
7882,7883,6d1adaC8060aEa6,Stephanie,Preston,Gonzalez-Farmer,Birdside,Norway,001-624-487-5218x657,001-557-791-8630,cesar59@harrison.info,2021-11-01,http://hopkins.com/
7893,7894,dBDF0Bd0E6eedd5,Gabriella,Ramsey,Powell PLC,Lake Joann,Norway,+1-127-978-7134x6546,589-175-0933,madison31@cohen-haney.biz,2020-02-24,http://pope.com/
7989,7990,a21FEe7B3e24bd0,Johnathan,Odonnell,Jefferson PLC,Lake Marissa,Norway,001-676-555-7333x2805,0646710348,kimberlygoodwin@james.com,2021-06-27,http://www.hood.biz/
8212,8213,4EAB3f9cfC43520,Shelia,Page,"Golden, Turner and Wolf",Josephfort,Norway,472.851.6574,4036500092,marissakaufman@sheppard.com,2020-06-29,https://thompson-cuevas.com/
8757,8758,fd3C4aF6af60DA2,Terrance,Randolph,Ramirez-Hoffman,Jacobsonberg,Norway,331.475.0387x216,+1-799-611-8568x52337,pollardronald@mcbride.net,2020-10-22,https://www.curtis.net/
9026,9027,aeFbeDF92fdbFd3,Thomas,Schneider,"Massey, Warner and Knapp",Port Bradleyfort,Norway,768-743-4708,0490679065,cunninghamkyle@rocha.info,2020-05-04,http://www.peters.com/
9042,9043,6B8577D1ac409CF,Alexa,Arias,Aguirre-Clay,North Jacksonchester,Norway,859.557.6047x8042,001-886-192-9826x84411,hector07@gallagher.com,2020-05-11,http://www.bauer.com/
9158,9159,Ff8Cd8103619Aa1,Brady,Rose,Zamora-Curtis,Port Hayley,Norway,(924)980-9392,310.948.2350x5600,callahantyrone@powers.com,2021-07-08,http://manning.com/
9566,9567,4ab7e95A7B9cFC0,Kara,Boyer,Gamble and Sons,Merrittview,Norway,(195)073-2278x746,+1-931-774-1860x21209,vpugh@francis.info,2021-04-05,https://salazar.com/
9958,9959,fCDd81Aa0cADD38,Caitlin,Tate,"Howe, Bates and Forbes",North Latoyafurt,Norway,5274550159,(586)291-2525x0018,gwendolynlam@chang.com,2021-09-29,http://gonzalez.com/
9995,9996,DD0caa06ebf217c,Meghan,Cline,Richardson LLC,Petersport,Cote d'Ivoire,001-270-136-4738x419,001-349-692-1755x055,nicolasandrade@bates.info,2022-04-27,http://thomas-ramos.com/

In [33]:
df.iloc[1]

Index                                       2
Customer Id                   10dAcafEBbA5FcA
First Name                           Kristina
Last Name                             Ferrell
Company              Horn, Shepard and Watson
City                               Aaronville
Country                               Andorra
Phone 1                          932-062-1802
Phone 2                    (209)172-7124x3651
Email                 xreese@hall-donovan.com
Subscription Date                  2020-04-27
Website              https://tyler-pugh.info/
Name: 1, dtype: object

In [34]:
df[["First Name", "Company" , "City"]]

     First Name                   Company              City
0       Heather              Mosley-David  Lake Jeffborough
1      Kristina  Horn, Shepard and Watson        Aaronville
2        Briana               Irwin-Oneal       East Jordan
3         Patty          Richardson Group  East Kristintown
4      Kathleen              Carson-Burch       Andresmouth
...         ...                       ...               ...
9995     Meghan            Richardson LLC        Petersport
9996   Jeremiah               Hodge-Nixon        Briggsport
9997      Peggy                  Vang LLC    West Joyceport
9998       Evan                 Gould Ltd    Camachochester
9999    Melissa              Burns-Holden        Sparkstown

[10000 rows x 3 columns]